name: Deploy and Run by Tags
env:
  REPO_NAME: ${{ github.event.repository.name }}
on:
  push:
    tags: ['v*.*.*']


permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Get tag'
      id: tag
      uses: 'devops-actions/action-get-tag@v1.0.3'

    - name: 'Login via Docker'
      uses: azure/docker-login@v2
      with:
        login-server: ${{ secrets.ACR_NAME_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.ACR_NAME_URL }}/${{env.REPO_NAME}}:${{ steps.tag.outputs.tag}}
        docker push ${{ secrets.ACR_NAME_URL }}/${{env.REPO_NAME}}:${{ steps.tag.outputs.tag }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: 'deploy Container Instance'
      uses: azure/aci-deploy@v1   # aci = azure container instance, no se puede escalar horizontalmente(crear mas instancias), si verticalmente (agregarle mas cpu o ram), sirve para hacer testeos.
                                  # aca = azure container app, se puede escalar horizontal y verticalmente
      with:
        location: eastus
        name: mycloudapp
        resource-group: recurso-aplicada
        image: ${{ secrets.ACR_NAME_URL }}/${{env.REPO_NAME}}:${{ steps.tag.outputs.tag }}
        dns-name-label: mycloudapp-${{ github.run_id }}-${{ steps.tag.outputs.tag }}
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        ports: 5000
        cpu: 1
        memory: 1
    
    - name: 'logout'
      run: |
        az logout
      